using UnityEngine;

public class BackgroundController : MonoBehaviour
{
    public Sprite backgroundSprite;
    private GameObject _bgObject;

    void Start()
    {
        Debug.Log("BackgroundController: Iniciant...");
        
        // 1. Crear l'objecte de fons si no existeix
        _bgObject = new GameObject("GameBackground_AutoGenerated");
        SpriteRenderer sr = _bgObject.AddComponent<SpriteRenderer>();
        
        // 2. Intentar carregar el sprite
        backgroundSprite = Resources.Load<Sprite>("backgroundLobby"); 
        
        if (backgroundSprite != null) {
            sr.sprite = backgroundSprite;
            Debug.Log("BackgroundController: Sprite 'backgroundLobby' carregat!");
        } else {
            Debug.LogError("BackgroundController: ERROR - No s'ha trobat 'backgroundLobby' a Assets/Resources/");
        }
        
        sr.sortingOrder = -100; // Ben al fons
        
        // 3. Ajustar mida - Fem-lo molt gran per assegurar que es veu
        _bgObject.transform.localScale = new Vector3(30f, 30f, 1f); 
    }

    void LateUpdate()
    {
        if (_bgObject != null && Camera.main != null) {
            Vector3 camPos = Camera.main.transform.position;
            // Posem el fons una mica per davant de la càmera (Z=0 sol ser el gameplay)
            // Si la càmera està a -10, la posem a Z=5 per exemple (entre càmera i samurái)
            // O a Z=10 si volem que estigui al fons del tot.
            _bgObject.transform.position = new Vector3(camPos.x, camPos.y, 5f); 
        }
    }
}
